---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ndn.tryu.dev
  resources:
  - addresssyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndn.tryu.dev
  resources:
  - addresssyncs/finalizers
  verbs:
  - update
- apiGroups:
  - ndn.tryu.dev
  resources:
  - addresssyncs/status
  verbs:
  - get
  - patch
  - update
