apiVersion: ndn.tryu.dev/v1alpha1
kind: AddressSync
metadata:
  name: nfd
  namespace: ndn
spec:
  watch:
    selector:
      matchLabels:
        app: nfd
  targets:
    - selector:
        matchLabels:
          app: manager
    - selector:
        matchLabels:
          app: seed
    - selector:
        matchLabels:
          app: function